Teste prova .net mvc4/Models/Aluno.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Teste_prova.net_mvc4.Models
{
    public class Aluno
    {        
        public int Id { get; set; }
        [Required]
        public string Nome { get; set; }
        [Required]
        public string Cpf { get; set; }
        [Required]
        public string Rg { get; set; }
        [Required]
        public DateTime DataNascimento { get; set; }
        public int Curso { get; set; }        
    }
}

Teste prova .net mvc4/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewModel.Models;
using System.Web.Script.Serialization;
using Servico.Servico;

namespace Teste_prova.net_mvc4.Controllers
{
    public class AlunoController : Controller
    {


        public ActionResult Cadastro()
        {
            Aluno aluno = new Aluno
            {
                Nome = "",
                Cpf = "",
                Rg = "",
                DataNascimento = System.DateTime.Now.ToString(),
                Curso = 1
            };
            return View(aluno);
        }

        
        public JsonResult Salvar(string dadosAluno, string dtNasc)
        {
            JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
            Aluno novoAluno = jsSerializer.Deserialize<Aluno>(dadosAluno);
            novoAluno.DataNascimento = dtNasc;            
            ServicoAluno servico = new ServicoAluno();            
            servico.salvarAluno(novoAluno);
            return Json(true);
        }

        public ActionResult Busca() {
            return View();
        }

        public JsonResult FazBusca(string palavraChave, string filtro)
        {
            ServicoAluno servico = new ServicoAluno();
            List<Aluno> aluno = servico.buscarAluno(palavraChave,filtro);
            
            if (aluno!= null)
            {
                JavaScriptSerializer jsSerializer = new JavaScriptSerializer();
                var novoJson = jsSerializer.Serialize( new  { 
                     Alunos = aluno                     
                });
                return Json(novoJson);                
            }
            else {
                return Json(null);
            }
            
        }

        public ActionResult Alterar()
        {
            return View();
        }

        public ActionResult Deletar()
        {

            return View();
        }        

    }
}

Teste prova .net mvc4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Teste_prova.net_mvc4.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }
        


    }
}

Teste prova .net mvc4/Views/Aluno/Alterar.cshtml
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <title>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body { padding-top: 60px; /* 60px to make the container go all the way
      to the bottom of the topbar */ }
    </style>    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
      </script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
    <style>
    </style>
  </head>
  <body>
 
    <div class="container">
      <div class="hero-unit">
        <div>
          <h1>
            Alterar
          </h1>
        </div>
      </div>
      <div class="well">
        <h4>
          Entre com os dados:
        </h4>
        <form>
          <div class="control-group">
            <label for="textinput1">
              Palavra-chave
            </label>
            <input name="textinput1" type="">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
            <label for="selectinput1">
              Filtro
            </label>
            <select name="selectinput1">
            </select>
          </div>
          <a class="btn btn-primary btn-large" href="#">
            Enviar
          </a>
        </form>
      </div>
      <div class="well">
        <h4>
          Entre com os dados:
        </h4>
        <form>
          <div class="control-group">
            <label for="textinput1">
              Nome
            </label>
            <input name="textinput1" type="">
          </div>
          <div class="control-group">
            <label for="textinput2">
              CPF
            </label>
            <input name="textinput2" type="">
          </div>
          <div class="control-group">
            <label for="textinput3">
              RG
            </label>
            <input name="textinput3" type="">
          </div>
          <div class="control-group">
            <label for="textinput4">
              Data nascimento
            </label>
            <input name="textinput4" type="">
          </div>
          <div class="control-group">
            <label for="selectinput1">
              Curso
            </label>
            <select name="selectinput1">
            </select>
          </div>
          <a class="btn btn-primary btn-large" href="#">
            Alterar
          </a>
        </form>
      </div>
    </div>

    <style>
      
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js">
    </script>        
  </body>
</html>

Teste prova .net mvc4/Views/Aluno/Busca.cshtml
@model ViewModel.Models.Aluno
<!DOCTYPE html>
<html lang="en">
  
  <head>
      <script src="~/Scripts/Aluno/busca-aluno.js" type="text/javascript"></script>
      <script src="~/Scripts/jquery-2.0.3.min.js" type="text/javascript"></script>
      <script src="~/Scripts/jquery.mask.min.js" type="text/javascript"></script>

    <meta charset="utf-8">
    <title>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body { padding-top: 60px; /* 60px to make the container go all the way
      to the bottom of the topbar */ }
    </style>    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
      </script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
    <style>
    </style>
  </head>
  <body onload="inicio()">
    
    <div class="container">
      <div class="hero-unit">
        <div>
          <h1>
            Busca
          </h1>
        </div>
      </div>
      <div class="well">
        <h4>
          Entre com os dados:
        </h4>
        <form>
          <div class="control-group">
            <label for="textinput1">
              Palavra-chave
            </label>
            <input name="textinput1" id="id-palavra"type="text" value=""/>
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
            <label for="selectinput1">
              Filtro
            </label>
            <select name="selectinput1" id="id-select">
                <option value="cpf">CPF</option>
                <option value="rg">RG</option>
            </select>
          </div>
          <a class="btn btn-primary btn-large" href="#" id="bt-busca">
            Enviar
          </a>
        </form>
      </div>
      <div class="well">
        <div>
              <h1>Tabela resultado</h1>
            <div class="place">
                <table class="table">
                    <tr>
                        <th>Id</th>                        
                        <th>Nome</th>
                        <th>Cpf</th>
                    </tr>                    
                </table>
            </div>
          </div>
        <div class="row-fluid">          
        </div>
      </div>
    </div>     
  </body>
</html>

Teste prova .net mvc4/Views/Aluno/Cadastro.cshtml
@model ViewModel.Models.Aluno


<script src="~/Scripts/Aluno/cadastro-aluno.js" type="text/javascript"></script>
<script src="~/Scripts/jquery-2.0.3.min.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.mask.min.js" type="text/javascript"></script>
 <body onload="inicio()">

 
    <div class="container">
      <div class="hero-unit">
        <div>
          <h1>
            Cadastro Aluno
          </h1>
        </div>
      </div>
      <div class="well">
        <h4>
          Entre com os dados:
        </h4>
       
            <div class="control-group">
            <label>Nome</label>
            <input type="text" id="id-nome" value="@Model.Nome"/>
          </div>
          <div class="control-group">
            <label>CPF</label>
            <input type="text" id="id-cpf" maxlength="14" value="@Model.Cpf"/>
          </div>
          <div class="control-group">
            <label>RG</label>
           <input type="text" id="id-rg" value="@Model.Rg"/>
          </div>
          <div class="control-group">
            <label>Data de Nascimento</label>
            <input type="text" id="id-dtNasc" value="@Model.DataNascimento"/>
          </div>
          <div class="control-group">
            <label>Curso</label>
            <select name="Nome do curso">
                <option value="1" >Biologia</option>
                <option value="2">Geografia</option>
            </select>        
          </div>            
            <input type="submit" value="Enviar" id="bt-salvar" class="btn btn-primary btn-large"/>                           
      </div>
    </div>
     </body>

Teste prova .net mvc4/Views/Aluno/Deletar.cshtml
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <title>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <style>
      body { padding-top: 60px; /* 60px to make the container go all the way
      to the bottom of the topbar */ }
    </style>    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
      </script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">
    <style>
    </style>
  </head>
  <body>
    <div class="container">
      <div class="hero-unit">
        <div>
          <h1>
            Deletar
          </h1>
        </div>
      </div>
      <div class="well">
        <h4>
          Entre com os dados:
        </h4>
        <form>
          <div class="control-group">
            <label for="textinput1">
              Palavra-chave
            </label>
            <input name="textinput1" type="">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
          </div>
          <div class="control-group">
            <label for="selectinput1">
              Filtro
            </label>
            <select name="selectinput1">
            </select>
          </div>
          <a class="btn btn-danger btn-large" href="#">
            Deletar
          </a>
        </form>
      </div>
      <div class="well">
        <div>
          <h1>
            Resultado:
          </h1>
        </div>
        <div class="row-fluid">
          <div class="span4">
          </div>
          <div class="span2">
          </div>
          <div class="span2">
          </div>
          <div class="span1">
          </div>
          <div class="span2">
          </div>
        </div>
      </div>
    </div>

    <style>
      
    </style>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js">
    </script>    
  </body>
</html>

Teste prova .net mvc4/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
  
  <head>
    <meta charset="utf-8">
    <title>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Le styles -->
    
 
    <style>
      body { padding-top: 60px; /* 60px to make the container go all the way
      to the bottom of the topbar */ }
    </style>
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js">
      </script>
    <![endif]-->
    <!-- Le fav and touch icons -->
    <style>
    </style>
  </head>
  <body>
    
    <div class="container-fluid">
    </div>
    <div class="hero-unit">
      <div>
        <h1>
          Teste prova .net mvc4
        </h1>
        <p>
          1) CRUD completo, sistema de cadastro de aluno (cadastro aluno)
        </p>
      </div>
    </div>


  </body>
</html>

Teste prova .net mvc4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
     <link href="~/assets/css/bootstrap.css" rel="stylesheet">
    <title></title>
</head>
    <body>
        <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                    </a>
                    <a class="brand" href="#">
                        Prova Um
                    </a>
                    <div class="nav-collapse">
                        <ul class="nav">
                            <li>
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li>
                                @Html.ActionLink("Cadastro", "Cadastro","Aluno")
                            </li>
                            <li>
                                @Html.ActionLink("Busca", "Busca","Aluno")
                            </li>
                            <li>
                                @Html.ActionLink("Alterar", "Alterar","Aluno")
                            </li>
                            <li>
                                @Html.ActionLink("Deletar", "Deletar","Aluno")
                            </li>
                        </ul>
                    </div>
                    <form class="navbar-form pull-right">
                    </form>
                </div>
            </div>
        </div>
        @RenderBody()     
        
        @RenderSection("scripts", required: false)
     
 
    </body>
</html>